### ISSUE TITLE
Add port command to get service host/ip

### ISSUE THREAD

**Issue by russ-c** [jbrekelmans/kube-compose#114]
In docker-compose, there is a "port" command which outputs the public port of a port binding.

The equivalent functionality in kube-compose would be to output the cluster IP or service hostname depending on a flag.

**Comment by xUnholy** [comment]
I don't personally like the name "port" as a command - we should consider something more meaningful even though docker-compose uses port. Perhaps align more with what kubectl would respect?

**Comment by jbrekelmans** [comment]
What would kubectl respect?
As discussed a `get` and `--format` would be nice, similar to the `--format` of `docker images`.
