### ISSUE TITLE
docker-compose.yml support for port range

### ISSUE THREAD

**Issue by xUnholy** [jbrekelmans/kube-compose#31]
Should be able to support a port range defined in docker-comose.yml

`version: '2'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80"
      - "8001-8010"
    volumes:
      - ./output/nginx/html:/usr/share/nginx/html:ro
      - ./output/nginx/conf.d:/etc/nginx/conf.d:ro`

**Comment by jbrekelmans** [comment]
Easiest approach is to port docker's logic as is: https://github.com/docker/docker-py/blob/master/docker/utils/ports.py (traced from docker-compose github)
