### ISSUE TITLE
docker-compose extends not supported

### ISSUE THREAD

**Issue by xUnholy** [jbrekelmans/kube-compose#38]
docker-compose.yml supports extends. In the below example service 1 should inherit service 2 environment variables.

`version: '2'

services:

  1:
    image: test:1
    extends:
      service: 2
    ports:
      - "1"

  2:
    image: test:2
    environment:
      TEST: 1
    ports:
      - "2"`

**Comment by russ-c** [comment]
For reference, https://docs.docker.com/compose/extends/
