### ISSUE TITLE
Add support for docker-compose.yml "restart" key on services

### ISSUE THREAD

**Issue by jbrekelmans** [jbrekelmans/kube-compose#85]
See https://docs.docker.com/compose/compose-file/compose-file-v2/#restart

**Comment by maheshrayas** [comment]
Default value of restartPolicy in PodSpec  is 'Always'
https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy

But Kube-compose sets restartPolicy: Never in podSpec
